### ISSUE TITLE
RLC-423 with older firmware stopped working with v0.27

### ISSUE THREAD

**Issue by skidank** [fwestenberg/reolink_dev#318]
I have multiple RLC-423 cameras with different firmware versions. The models with firmware v2.0.0.1441_19032111_v1.0.0.30 stopped working with v0.27 (show as unavailable). The models with firmware v3.0.0.146_20122309 continue to work as usual. Tried both rtsp and rtmp, same results. Reverting to 0.26 fixes the problem.  Home Assistant version is 2021.10.5.

This appears in the logs:

```
Logger: homeassistant.config_entries
Source: deps/lib/python3.9/site-packages/reolink/software_version.py:40
First occurred: 10:46:01 AM (2 occurrences)
Last logged: 10:46:01 AM

Error setting up entry Porch for reolink_dev
Error setting up entry BackYard for reolink_dev
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/reolink_dev/__init__.py", line 73, in async_setup_entry
    if not await base.connect_api():
  File "/config/custom_components/reolink_dev/base.py", line 198, in connect_api
    if not await self._api.get_states():
  File "/config/deps/lib/python3.9/site-packages/reolink/camera_api.py", line 362, in get_states
    if not self._is_nvr and self._sw_version_object < ref_sw_version_3_1_0_0_0:
  File "/config/deps/lib/python3.9/site-packages/reolink/software_version.py", line 110, in __gt__
    return self.is_greater_than(other)
  File "/config/deps/lib/python3.9/site-packages/reolink/software_version.py", line 40, in is_greater_than
    if self.major > target_version.major:
AttributeError: 'NoneType' object has no attribute 'major'
```
