### ISSUE TITLE
binary motion sensor not working with RLC-810A - HA2021.7.3

### ISSUE THREAD

**Issue by dncex** [fwestenberg/reolink_dev#227]
Home Assistant:
Core version: core-2021.7.3
reolink_dev: version as of 21/07/2021 (commit: a3907d1d620f9ca8052682c22eb4d6faab05c561)

Camera Model: RLC-810A   (6 cameras, no NVR)
Firmware Version: v3.0.0.412_21063003   (14 july 2021)

Issues I've found:
- binary motion sensors not working (i am interested in person detection)
- live stream not working (I've tried all 4 combinations rtmp/rtsp main/sub) 

Error log:
Logger: aiohttp.server
Source: custom_components/reolink_dev/camera.py:198
Integration: Reolink IP camera (documentation, issues)
First occurred: 7:04:29 PM (2 occurrences)
Last logged: 7:06:14 PM

Error handling request
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/forwarded.py", line 77, in forwarded_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/camera/__init__.py", line 511, in get
    return await self.handle(request, camera)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/camera/__init__.py", line 546, in handle
    stream = await camera.handle_async_mjpeg_stream(request)
  File "/home/homeassistant/.homeassistant/custom_components/reolink_dev/camera.py", line 198, in handle_async_mjpeg_stream
    stream = CameraMjpeg(self._manager.binary)
AttributeError: 'ReolinkCamera' object has no attribute '_manager'

**Comment by ShlomiPorush** [comment]
Same here with: RLC-820A

**Comment by vodopives** [comment]
Same here. Same camera: RLC-810A.

The live stream not working for me is the worst...

**Comment by ShlomiPorush** [comment]
> The live stream not working for me is the worst...

Change configuration to sub stream and rtsp.

**Comment by fwestenberg** [comment]
I also own a RL810-A, working with sub stream and RTMP

**Comment by fwestenberg** [comment]
In version v0.19 the error `AttributeError: 'ReolinkCamera' object has no attribute '_manager'` should be fixed.

**Comment by vodopives** [comment]
Updated to v0,19 and now it works.
Thanks a lot!

**Comment by ShlomiPorush** [comment]
Well. Mine after the update still doesn't work 
![Screenshot_20210728-224404](https://user-images.githubusercontent.com/5992161/127386032-a2f705c7-6ec7-408a-b337-f59879d49cd2.jpg)

**Comment by vodopives** [comment]
Binary sensor working fine here after the update as well.

**Comment by dncex** [comment]
still no luck in my case (maybe because I am running home assistant in a venv).
Nor binary motion sensor nor live stream are working.

This is my log:

Logger: aiohttp.server
Source: custom_components/reolink_dev/camera.py:199
Integration: Reolink IP camera (documentation, issues)
First occurred: 9:15:48 AM (2 occurrences)
Last logged: 9:15:51 AM

Error handling request
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/forwarded.py", line 77, in forwarded_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/camera/__init__.py", line 511, in get
    return await self.handle(request, camera)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/camera/__init__.py", line 546, in handle
    stream = await camera.handle_async_mjpeg_stream(request)
  File "/home/homeassistant/.homeassistant/custom_components/reolink_dev/camera.py", line 199, in handle_async_mjpeg_stream
    await stream.open_camera(self._input, extra_cmd=self._extra_arguments)
AttributeError: 'ReolinkCamera' object has no attribute '_input'

**Comment by vodopives** [comment]
> Binary sensor working fine here after the update as well.

Live feed and binary sensor stoped working after a couple of days working with the v0.19.

Logs:
This error originated from a custom integration.

Logger: custom_components.reolink_dev.base
Source: custom_components/reolink_dev/base.py:339
Integration: Reolink IP camera (documentation, issues)
First occurred: 23:24:15 (4 occurrences)
Last logged: 23:25:15

Host 192.168.1.64 error renewing the Reolink subscription
Host 192.168.1.65 error renewing the Reolink subscription

**Comment by fernando155** [comment]
I got the same problem with the motion sensors. None of them is working. The camera snapshots are working good, and the live feeds, but not the motion sensors.

The problem in my case is I dont have any "errors" in my log. As well is very strange because I have another motion sensor outside, connected with zigbee, and it does not work too (it reports temp, lux, even ocuppancy, but not motion). I don´t know if maybe the problem is coming from somewhere else...

**Comment by polo1469** [comment]
I'm having the same problem as dncex. I have the 
- binary motion sensors not working (i am interested in person/car detection)
- live stream not working (I've tried all 4 combinations rtmp/rtsp main/sub, I get a "User input malformed" if I try to change anything. Added file to show this)
![User input malformed](https://user-images.githubusercontent.com/62172446/129264036-80f20bce-4e61-446a-84f6-c064189fd987.jpg)

I have
Home Assistant:
Core version: core-2021.8.6
reolink integration: version 0.19 

Camera Model: RLC-820A (1 camera, no NVR)
Firmware Version: v3.0.0.250_21040801 (21st Jan. 2021)

I can make fine snapshots from the camera. 

Hope anyone has a idea to get the stream and motion sensor to work

**Comment by rodakswe** [comment]
Did you have the chance to test with the august firmware?

**Comment by dncex** [comment]
> Did you have the chance to test with the august firmware?

yes... same issues running latest firmware v3.0.0.494

**Comment by nmummau** [comment]
I'm having this same issue. And from some troubleshooting here is what I've found.

Reolink says on [their support page](https://support.reolink.com/hc/en-us/articles/360007010473-How-to-Live-View-Reolink-Cameras-via-VLC-Media-Player) that when using the RLC-820A you should use the h265 stream:
>Note: Since the Video Format for the new 8mp model RLC-810A , RLC-820A& RLC-1220A is H.265, if you want to see main RTSP stream, please change ‘’h264“to “h265“.

Using VLC I am able to test this successfully using my rtsp url as:
`rtsp://****:****@192.168.40.11:554/**h265**Preview_01_main`
Emphasis on **h265**!

When using "h264" in the url with VLC, it does not work:
`rtsp://****:****@192.168.40.11:554/h264Preview_01_main`
___
Now go over to Home Assistant. I've successfully configured this  Reolink IP camera integration using HACS. As an eqivalent test I configured it using the 'RTSP' protocol and the 'main' stream.
This results in me getting the following error:
`Error opening stream rtsp://****:****@192.168.40.11:554/h264Preview_01_main`
Emphasis on **h264**!
___

So how can I make this reolink_dev integration us the "h265" rtsp stream?

I guess the above is only helpful to troubleshoot the rtsp stream. I have no idea how to troubleshoot the RTMP protocol. I get the following error when trying to use RTMP:
```Error opening stream rtmp://192.168.40.11:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=****&password=****```

**Comment by nmummau** [comment]
To followup on my last post, I did get the live stream working! I used the approach outlined in a [different issue's comment](https://github.com/fwestenberg/reolink_dev/issues/211#issuecomment-889516560).

Protocol: rtmp
Stream: sub
Motion: 60
Playback Range: 2
Custom Thumbnail path: /
Timeout: 30

![image](https://user-images.githubusercontent.com/10524529/132436522-cfafecae-d3f7-464a-8dce-9b301ce3fa01.png)

**Comment by dncex** [comment]
I suppose that all the different behaviour we are having are due to the different camera firmwares... not the integration itself

**Comment by pod31** [comment]
Hi, i have a RLC-822A, i configure the integration (0.22) with rtmp, sub, h264, 60, 2 and /
The video works fine
But sensors like motion, person detected, pet detected, vehicle detected are never update with motion detection of the camera.
Also, the toggle buttons like FTP, IR lights, email, push notifications, record audio, recording are not necessarily in the good states.

**Comment by cpainchaud** [comment]
hi @pod31  please open your own issue and provides logs according to the template. Ensure as well that you have latest firmware running.

**Comment by cpainchaud** [comment]
@fwestenberg to finish with last error message:
`File "/home/homeassistant/.homeassistant/custom_components/reolink_dev/camera.py", line 199, in handle_async_mjpeg_stream
await stream.open_camera(self._input, extra_cmd=self._extra_arguments)
AttributeError: 'ReolinkCamera' object has no attribute '_input'`

I just can't find what 'self._input' is supposed to be, this variable exists nowhere and I lack the context to fix it myself. Do you mind having a quick look to tell what should be the real variable ?

**Comment by dncex** [comment]
now I am on the latest firmare (commit: 2dbbce40ce8d01274e965bb772e128ed36cce841), with the lastest camera firmware: v3.0.0.494.
Running HA 2021.9.7
Unfortunately the binary sensor are not working yet; this is the log

  File "/srv/homeassistant/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/forwarded.py", line 89, in forwarded_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/camera/__init__.py", line 590, in get
    return await self.handle(request, camera)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/camera/__init__.py", line 630, in handle
    stream = await camera.handle_async_mjpeg_stream(request)
  File "/home/homeassistant/.homeassistant/custom_components/reolink_dev/camera.py", line 200, in handle_async_mjpeg_stream
    await stream.open_camera(self._input, extra_cmd=self._extra_arguments)
AttributeError: 'ReolinkCamera' object has no attribute '_input'


Anyhow many thanks for this update: having specific binary sensor (person, vehicle,..) is what I was looking for!
